version: '3.7'
networks:
  botalista-dev-bridge:
    external: true
services:
  cit-ticketing:
    image: registry.botalista-dev.ch/cit-ticketing:dev
    networks:
      - botalista-dev-bridge
    environment:
    - app.admin.mail=cyril.boillat@ville-ge.ch
    - app.github.user=CJB-Geneve
    - app.github.repository=cit-ticketing
    - app.github.token=${TOKEN_GITHUB}
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128MB
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

    
    