version: '3.3'
networks:
  bota_rc_gateway:
    external: true
  bota_sandbox_gateway:
    external: true
  bota_neu_prd_gateway:
    external: true
  bota_jbp_prd_gateway:
    external: true
  bota_bern_prd_gateway:
    external: true
  bota_g_prd_gateway:
    external: true
  bota_wfo_prd_gateway:
    external: true
  bota_msm_gateway:
    external: true
  bota_ncy_prd_gateway:
    external: true
services:
  cit-ticketing:
    image: registry.botalista-dev.ch/cit-ticketing:latest
    networks:
    - bota_rc_gateway
    - bota_sandbox_gateway
    - bota_neu_prd_gateway
    - bota_jbp_prd_gateway
    - bota_bern_prd_gateway
    - bota_g_prd_gateway
    - bota_wfo_prd_gateway
    - bota_msm_gateway
    - bota_ncy_prd_gateway
    environment:
    - app.admin.mail=cyril.boillat@ville-ge.ch
    - app.github.user=CJB-Geneve
    - app.github.repository=cit-ticketing
    - app.github.token=${TOKEN_GITHUB}
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128MB
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s